### ISSUE TITLE
Password appears in plain text in console and error log

### ISSUE THREAD

**Issue by ddetton** [jbasen/Crestron-MyQ#1]
For security reasons, probably should mask the password when posting to the console and error log.

**Comment by jbasen** [comment]
Thanks for pointing that out.  However, I'm just writing these modules for
people's personal use and giving them away for free.  I don't even get paid
for writing the articles.  It is just my way of giving back to the smart
home community.

My goal when I write modules is to include full capabilities for
debugging.  If MyQ changes the protocol, which they have been known to do
in the past breaking integrations, I may, or may not, be in a position to
fix the issue.  That is why I included full source code.

In addition, nothing gets written to the console or error log unless the
programmer is setting the Debug_Msg_Output parameter to do so.  And, since
the username and password is already entered as parameters in the module,
the programmer already has access to them.

Jay

**Comment by jbasen** [comment]
I've removed the display of the username/password in the console debugging display
